services:
  blob:
    url: https://lopcopsiamobjects.blob.core.windows.net
    headers:

      x-ms-version: "2020-04-08"
    credentials:
      oauth2:
        token_url: "https://login.microsoftonline.com/bb047546-786f-4de1-bd75-24e5b6f79043/oauth2/v2.0/token"
        client_id: "11fa411f-5433-4642-8ad0-2d743d6b44d0"
        client_secret: "2Tp8Q~BSCyQ-2HGPHOmtzrodHlIU7dNzRMRjFbyH"
        scopes:
          - https://storage.azure.com/.default

bundles:
  authz:
    service: blob
    resource: opa-policies-aurora/bundle.tar.gz